# Dagster libraries to run both dagit and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.7-slim

RUN pip install \
    dagster==0.14.0 \
    dagster-graphql==0.14.0 \
    dagit==0.14.0 \
    dagster-postgres \
    dagster-docker \
    markupsafe==2.0.1 \
    ipython_genutils \
    'protobuf<=3.19'

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
