#1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./ui/package.json ./ui/yarn.lock ./
COPY ./ui/src ./src
COPY ./ui/public ./public
RUN yarn install
RUN yarn build

#2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY nginx/nginx.default.conf /etc/nginx/conf.d/default.conf
