FROM ubuntu:20.04

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-get update && apt-add-repository -y ppa:libreoffice
RUN apt-get update && apt-get install -y libreoffice
RUN apt-get update && apt-get install -y python3-pip python3-dev \
&& cd /usr/local/bin \
&& ln -s /usr/bin/python3 python \
&& pip3 --no-cache-dir install --upgrade pip \
&& rm -rf /var/lib/apt/lists/*

COPY ./backend backend
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt
WORKDIR backend

# Start the server
ENTRYPOINT ["python"]
CMD ["-u", "app.py"]
