FROM ubuntu:latest

RUN apt-get update \
&& apt-get install -y python3-pip python3-dev \
&& cd /usr/local/bin \
&& ln -s /usr/bin/python3 python \
&& pip3 --no-cache-dir install --upgrade pip \
&& rm -rf /var/lib/apt/lists/* \
&& pip install \
    flask \
    sqlalchemy \
    marshmallow \
    flask-restful \
    psycopg2-binary \
    pandas \
    sqlalchemy-utils \
    dagster==0.14.0 \
    dagster_graphql==0.14.0 \
    markupsafe==2.0.1 \
    pydantic

COPY ./backend backend
WORKDIR backend

# Start the server
ENTRYPOINT ["python"]
CMD ["-u", "app.py"]
